INSERT INTO tb_topico (titulo, mensagem, autor, curso, data_criacao, status) VALUES
('Diferença entre Java e JavaScript', 'Quais são as principais diferenças entre Java e JavaScript?', 'Carlos', 'Desenvolvimento Web', '2024-04-10 14:23:00', 1),
('Melhores práticas em Python', 'Quais são algumas das melhores práticas para escrever código em Python?', 'Ana', 'Desenvolvimento de Software', '2024-04-11 09:15:00', 1),
('Como usar Async/Await em JavaScript', 'Alguém pode explicar como funciona o Async/Await em JavaScript?', 'João', 'Programação Web', '2024-04-12 17:45:00', 1),
('Instalação do Node.js', 'Qual é a melhor forma de instalar o Node.js no Ubuntu?', 'Mariana', 'Programação de Servidores', '2024-04-13 11:30:00', 1),
('Diferenças entre SQL e NoSQL', 'Quais são as principais diferenças entre bancos de dados SQL e NoSQL?', 'Pedro', 'Bancos de Dados', '2024-04-14 15:00:00', 1),
('Introdução ao React', 'Como começar a desenvolver com React?', 'Fernanda', 'Desenvolvimento Front-end', '2024-04-15 13:20:00', 1),
('Problemas de performance com CSS', 'Como resolver problemas de performance com CSS em projetos grandes?', 'Lucas', 'Web Design', '2024-04-16 08:55:00', 1),
('Melhor editor de código para Java', 'Qual é o melhor editor de código para programar em Java?', 'Patrícia', 'Desenvolvimento de Software', '2024-04-17 19:40:00', 1),
('Uso de Docker para DevOps', 'Quais são os benefícios de usar Docker em um ambiente DevOps?', 'Renato', 'DevOps', '2024-04-18 07:10:00', 1),
('Dúvidas sobre Git e GitHub', 'Como faço para resolver conflitos de merge no Git?', 'Camila', 'Controle de Versão', '2024-04-19 14:50:00', 1),
('Introdução ao Machine Learning', 'Quais são os primeiros passos para aprender Machine Learning?', 'Ricardo', 'Inteligência Artificial', '2024-04-20 10:05:00', 1),
('Diferença entre REST e GraphQL', 'Quais são as principais diferenças entre APIs REST e GraphQL?', 'Juliana', 'Desenvolvimento de APIs', '2024-04-21 16:30:00', 1),
('Deploy de Aplicações com Kubernetes', 'Como fazer o deploy de aplicações usando Kubernetes?', 'Gustavo', 'Orquestração de Contêineres', '2024-04-22 09:20:00', 1),
('Uso de Express.js com MongoDB', 'Como conectar uma aplicação Express.js a um banco de dados MongoDB?', 'Leandro', 'Desenvolvimento de Back-end', '2024-04-23 18:45:00', 1),
('Melhores práticas em C++', 'Quais são algumas das melhores práticas ao programar em C++?', 'Tatiana', 'Desenvolvimento de Software', '2024-04-24 12:10:00', 1),
('Diferença entre compilador e interpretador', 'Qual é a diferença entre um compilador e um interpretador?', 'Fernando', 'Teoria da Computação', '2024-04-25 15:55:00', 1),
('Instalação do ambiente de desenvolvimento para Ruby on Rails', 'Qual é a melhor forma de instalar um ambiente de desenvolvimento para Ruby on Rails?', 'Bianca', 'Desenvolvimento Web', '2024-04-26 13:35:00', 1),
('Introdução ao TypeScript', 'Como começar a programar em TypeScript?', 'Roberto', 'Desenvolvimento Web', '2024-04-27 08:25:00', 1),
('Dúvidas sobre Python Pandas', 'Como manipular DataFrames em Python usando a biblioteca Pandas?', 'Silvia', 'Análise de Dados', '2024-04-28 17:50:00', 1),
('Como otimizar consultas SQL', 'Quais são as melhores práticas para otimizar consultas SQL?', 'Marcelo', 'Bancos de Dados', '2024-04-29 14:05:00', 1);