INSERT INTO tb_topico (titulo, mensagem, autor, curso, data_criacao, status) VALUES
('Introdução ao Docker', 'Como começar a usar Docker para desenvolvimento?', 'Bruno', 'DevOps', '2015-03-15 10:20:00', 1),
('Vantagens do uso de TypeScript', 'Quais são as vantagens de usar TypeScript sobre JavaScript?', 'Carla', 'Desenvolvimento Web', '2016-05-22 14:50:00', 1),
('Frameworks para desenvolvimento em Python', 'Quais são os melhores frameworks para desenvolvimento web em Python?', 'Diego', 'Desenvolvimento de Software', '2017-07-10 09:35:00', 1),
('Diferenças entre SASS e LESS', 'Quais são as principais diferenças entre SASS e LESS?', 'Eduarda', 'Web Design', '2018-02-18 13:45:00', 1),
('Configuração do ambiente de desenvolvimento para Node.js', 'Qual é a melhor forma de configurar o ambiente de desenvolvimento para Node.js?', 'Fábio', 'Programação de Servidores', '2019-06-05 17:20:00', 1),
('Uso de bibliotecas JavaScript em projetos grandes', 'Como gerenciar bibliotecas JavaScript em projetos de grande escala?', 'Gisele', 'Desenvolvimento Web', '2020-08-11 11:10:00', 1),
('Melhores práticas para testes unitários em Java', 'Quais são as melhores práticas para escrever testes unitários em Java?', 'Henrique', 'Desenvolvimento de Software', '2021-01-27 16:55:00', 1),
('Introdução ao Vue.js', 'Como iniciar um projeto com Vue.js?', 'Isabel', 'Desenvolvimento Front-end', '2022-04-12 09:00:00', 1),
('O que são microserviços?', 'Como funciona a arquitetura de microserviços?', 'Jorge', 'Arquitetura de Software', '2023-05-19 14:25:00', 1),
('Configuração de banco de dados MySQL', 'Como configurar um banco de dados MySQL para uma aplicação web?', 'Karen', 'Bancos de Dados', '2015-11-03 18:45:00', 1),
('Principais recursos do Java 8', 'Quais são os principais recursos introduzidos no Java 8?', 'Leonardo', 'Desenvolvimento de Software', '2016-09-29 08:30:00', 1),
('Automatização de tarefas com Ansible', 'Como usar Ansible para automatizar tarefas de TI?', 'Mariana', 'DevOps', '2017-12-14 11:15:00', 1),
('Uso de WebAssembly', 'Quais são as vantagens de usar WebAssembly em aplicações web?', 'Nicolas', 'Desenvolvimento Web', '2018-07-08 15:40:00', 1),
('Segurança em aplicações Django', 'Quais são as melhores práticas para segurança em aplicações Django?', 'Olívia', 'Desenvolvimento de Software', '2019-03-25 13:05:00', 1),
('Desenvolvimento de jogos com Unity', 'Como começar a desenvolver jogos com Unity?', 'Paulo', 'Desenvolvimento de Jogos', '2020-10-14 17:50:00', 1),
('Integração contínua com Jenkins', 'Como configurar um pipeline de integração contínua com Jenkins?', 'Quirino', 'DevOps', '2021-06-30 10:20:00', 1),
('Desempenho de consultas em MongoDB', 'Como otimizar o desempenho de consultas no MongoDB?', 'Renata', 'Bancos de Dados', '2022-02-11 16:30:00', 1),
('Deploy de aplicações com Heroku', 'Como fazer o deploy de uma aplicação web no Heroku?', 'Samuel', 'Desenvolvimento de Software', '2023-09-23 08:45:00', 1),
('Melhores práticas para CSS modularizado', 'Quais são as melhores práticas para escrever CSS modularizado?', 'Tatiane', 'Web Design', '2015-04-17 14:10:00', 1),
('Uso de GraphQL em APIs', 'Quais são as vantagens de usar GraphQL em vez de REST?', 'Ubiratan', 'Desenvolvimento de APIs', '2016-12-05 19:55:00', 1);
